name: Taging Version Code

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          # Download yq binary
          YQ_VERSION=v4.33.2
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Extract version from pubspec.yaml
        id : get_version
        run: |
          VERSION=$(yq eval '.version' pubspec.yaml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check which branch is being pushed to
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            git tag "v${{ env.VERSION }}-main"
          elif [ "${GITHUB_REF#refs/heads/}" == "dev" ]; then
            git tag "v${{ env.VERSION }}-dev"
          else
            git tag "v${{ env.VERSION }}-other"
          fi
          git push origin --tags