name: Taging Version Code

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install yq
        run: |
          # Download yq binary
          YQ_VERSION=v4.33.2
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check version 
          PREVIOUS_VERSION_RAW=$(git show HEAD~1:pubspec.yaml | yq eval '.version')
          IFS='+' read -r PREVIOUS_VERSION PREVIOUS_VERSION_CODE <<< "$PREVIOUS_VERSION_RAW"
          echo "PREVIOUS_VERSION: $PREVIOUS_VERSION"
          echo "PREVIOUS_VERSION_CODE: $PREVIOUS_VERSION_CODE"
          
          CURRENT_VERSION_RAW=$(yq eval '.version' pubspec.yaml)
          IFS='+' read -r CURRENT_VERSION CURRENT_VERSION_CODE <<< "$CURRENT_VERSION_RAW"
          echo "CURRENT_VERSION: $CURRENT_VERSION"
          echo "CURRENT_VERSION_CODE: $CURRENT_VERSION_CODE"
          
          if [[ "$PREVIOUS_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "version same"
          else
            echo "version change"
            git tag "v${CURRENT_VERSION}-dev"
            git push origin --tags
          fi